/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('view-ui-plus/src/components/button/button.vue')['default']
    ButtonGroup: typeof import('view-ui-plus/src/components/button-group')['default']
    Card: typeof import('view-ui-plus/src/components/card/card.vue')['default']
    ColorPicker: typeof import('view-ui-plus/src/components/color-picker/color-picker.vue')['default']
    CountUp: typeof import('view-ui-plus/src/components/count-up/count-up.vue')['default']
    DatePicker: typeof import('view-ui-plus/src/components/date-picker')['default']
    Form: typeof import('view-ui-plus/src/components/form/form.vue')['default']
    FormItem: typeof import('view-ui-plus/src/components/form-item')['default']
    FullPop: typeof import('./src/components/FullPop/FullPop.vue')['default']
    HeaderBt: typeof import('./src/components/HeaderBt/HeaderBt.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Icon: typeof import('view-ui-plus/src/components/icon/icon.vue')['default']
    IconTxtBtn: typeof import('./src/components/IconTxtBtn/IconTxtBtn.vue')['default']
    Input: typeof import('view-ui-plus/src/components/input/input.vue')['default']
    Numeral: typeof import('view-ui-plus/src/components/numeral/numeral.vue')['default']
    Option: typeof import('view-ui-plus/src/components/option')['default']
    Page404: typeof import('./src/components/Page404/Page404.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('view-ui-plus/src/components/scroll/scroll.vue')['default']
    Select: typeof import('view-ui-plus/src/components/select/select.vue')['default']
    ShowHidePanel: typeof import('./src/components/ShowHidePanel/ShowHidePanel.vue')['default']
    ShowHidePanelB: typeof import('./src/components/ShowHidePanelB/ShowHidePanelB.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu/SideMenu.vue')['default']
    SideMenuGroup: typeof import('./src/components/SideMenu/SideMenuGroup.vue')['default']
    Table: typeof import('view-ui-plus/src/components/table/table.vue')['default']
    TableIconBtn: typeof import('./src/components/TableIconBtn/TableIconBtn.vue')['default']
    TableSearch: typeof import('./src/components/TableSearch/TableSearch.vue')['default']
    Time: typeof import('view-ui-plus/src/components/time/time.vue')['default']
    TimePicker: typeof import('view-ui-plus/src/components/time-picker')['default']
    Tooltip: typeof import('view-ui-plus/src/components/tooltip/tooltip.vue')['default']
  }
}
