/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('view-ui-plus/src/components/button/button.vue')['default']
    Checkbox: typeof import('view-ui-plus/src/components/checkbox/checkbox.vue')['default']
    CheckboxGroup: typeof import('view-ui-plus/src/components/checkbox-group')['default']
    Icon: typeof import('view-ui-plus/src/components/icon/icon.vue')['default']
    Input: typeof import('view-ui-plus/src/components/input/input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
